data:
  name: v2_35

  labels: {backward":0,"bed":1,"bird":2,"cat":3,"dog":4,"down":5,"eight":6,"five":7,"follow":8,"forward":9,"four":10,"go":11,
              "happy":12,"house":13,"learn":14,"left":15,"marvin":16,"nine":17,"no":18,"off":19,"on":20,"one":21,"right":22,"seven":23,"sheila":24,"six":25,"stop":26,
                  "three":27,"tree":28,"two":29,"up":30,"visual":31,"wow":32,"yes":33,"zero":34}
  train : 'egs/speech_commands/manifest/train'
  valid : 'egs/speech_commands/manifest/valid'
  test : 'egs/speech_commands/manifest/test'
  
  batch_size: 16 
  num_mel_bins: 40
  normalization: True
  spec_augment: True
  speed_perturb: True
  gaussian_noise: 0.00
  num_workers: 4
  spec_augment_config:
    freq_mask_num: 2
    time_mask_num: 5
    freq_mask_rate: 0.3
    time_mask_rate: 0.05

model:
  type: transformer
  front_end_type : None
  frontend:
    input_size: 40
    output_size: 256
    in_channel: 1
    mid_channel: 64
    out_channel: 128
    kernel_size: [[3,3],[3,3]]
    stride: [2, 2]
    dropout: 0.0
    act_func_type: relu
    front_end_layer_norm: False
    
  encoder_type: transformer
  encoder:
    d_model: 256
    n_heads: 4
    d_ff: 2048
    n_blocks: 12
    pos_dropout: 0.0 
    slf_attn_dropout: 0.0
    ffn_dropout: 0.0
    residual_dropout: 0.1
    normalize_before: False
    concat_after: False
    activation: glu
    relative_positional: False
train:
  optimizer_type: adam
  optimizer:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 1.0e-6
    amsgrad: False
  scheduler_type: cosine
  scheduler:
    warmup_steps: 12000
    factor: 1.0
  clip_grad: 5
  epochs: 80
  accum_steps: 4
  grad_noise: 0.0
  load_model: False
  save_name: transformer_v2_35
